#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Prometheus exporter for Ceph RADOS Gateway (RGW).

Exports usage-log, bucket, user and account (Squid / Tentacle and newer)
metrics gathered through the RGW Admin Ops API.
"""

import argparse
import base64
import email.utils
import hashlib
import hmac
import json
import logging
import os
import re
import sys
import threading
import time
import urllib.parse
import warnings
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor

import requests
from prometheus_client import start_http_server
from prometheus_client.core import REGISTRY, CounterMetricFamily, GaugeMetricFamily
from urllib3.util.retry import Retry

# Account IDs generated by RGW look like "RGW" followed by 17 digits.
ACCOUNT_ID_RE = re.compile(r"^RGW\d{17}$")

# Page size for paginated listings (users, metadata keys).
LIST_PAGE_SIZE = 1000

ALL_COLLECTORS = ("usage", "buckets", "users", "accounts")


class S3V2Auth(requests.auth.AuthBase):
    """
    Minimal AWS Signature Version 2 signer. Admin Ops requests are plain
    GETs without sub-resources, so only the request path is signed.
    """

    def __init__(self, access_key, secret_key):
        self.access_key = access_key
        self.secret_key = secret_key.encode("utf-8")

    def __call__(self, r):
        date = email.utils.formatdate(usegmt=True)
        r.headers["Date"] = date
        path = urllib.parse.urlsplit(r.url).path
        string_to_sign = "\n".join(
            [
                r.method,
                r.headers.get("Content-MD5", ""),
                r.headers.get("Content-Type", ""),
                date,
                path,
            ]
        )
        digest = hmac.new(
            self.secret_key, string_to_sign.encode("utf-8"), hashlib.sha1
        ).digest()
        signature = base64.b64encode(digest).decode("utf-8")
        r.headers["Authorization"] = "AWS {0}:{1}".format(self.access_key, signature)
        return r


def _num(value, default=0):
    """Coerce JSON values (bool / int / str) to a number for Prometheus."""
    if value is None:
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _tag_label(tag):
    """Turn a bucket tag key into a valid Prometheus label name."""
    return "tag_" + re.sub(r"[^a-zA-Z0-9_]", "_", tag)


class RADOSGWCollector(object):
    """RADOSGWCollector gathers usage, bucket, user and account data from
    the specified RADOSGW and presents it in a format suitable for pulling via
    a Prometheus server.

    NOTE: By default RADOSGW Servers do not gather usage data and it must be
    enabled by 'rgw enable usage log = true' in the appropriate section
    of ceph.conf see Ceph documentation for details"""

    def __init__(
        self,
        host,
        admin_entry,
        access_key,
        secret_key,
        store,
        insecure,
        timeout,
        tag_list,
        signature="v4",
        region="us-east-1",
        threads=10,
        collectors=ALL_COLLECTORS,
        interval=60,
        retries=3,
    ):
        super(RADOSGWCollector, self).__init__()
        self.host = host
        self.access_key = access_key
        self.secret_key = secret_key
        self.store = store
        self.insecure = insecure
        self.timeout = float(timeout)
        self.tags = [t.strip() for t in tag_list.split(",") if t.strip()]
        self.threads = max(1, int(threads))
        self.collectors = set(collectors)
        self.interval = float(interval)
        self.retries = max(0, int(retries))

        # helpers for default schema
        if not self.host.startswith("http"):
            self.host = "http://{0}".format(self.host)
        # and for request_uri
        if not self.host.endswith("/"):
            self.host = "{0}/".format(self.host)

        self.url = "{0}{1}/".format(self.host, admin_entry.strip("/"))

        if signature == "v2":
            self.auth = S3V2Auth(access_key, secret_key)
        else:
            from requests_aws4auth import AWS4Auth

            self.auth = AWS4Auth(access_key, secret_key, region, "s3")

        self._lock = threading.Lock()
        # Serializes scrapes: metric state lives on the instance.
        self._scrape_lock = threading.Lock()
        # Last metrics gathered by the background thread.
        self._cache = []
        # Prepare Requests Session
        self._session()

    def describe(self):
        """
        Returning an empty list prevents prometheus_client from calling
        collect() (and hitting RGW) when the collector is registered.
        """
        return []

    def collect(self):
        """
        With a positive interval, serve the metrics gathered by the
        background thread so that /metrics answers instantly no matter how
        many users/buckets the cluster has. Otherwise query RGW on each
        scrape.
        """
        if self.interval > 0:
            return list(self._cache)
        return self._scrape()

    def start_background(self):
        """
        Refresh the metric cache every 'interval' seconds in a daemon thread.
        """
        if self.interval <= 0:
            return

        def loop():
            while True:
                start = time.time()
                try:
                    self._cache = self._scrape()
                except Exception:
                    logging.exception("Scrape failed, keeping previous metrics")
                time.sleep(max(0, self.interval - (time.time() - start)))

        threading.Thread(target=loop, name="rgw-scraper", daemon=True).start()

    def _scrape(self):
        with self._scrape_lock:
            return list(self._scrape_unlocked())

    def _scrape_unlocked(self):
        """
        * Collect 'usage' data:
            https://docs.ceph.com/en/latest/radosgw/adminops/#get-usage
        * Collect 'bucket' data:
            https://docs.ceph.com/en/latest/radosgw/adminops/#get-bucket-info
        * Collect 'user' data:
            https://docs.ceph.com/en/latest/radosgw/adminops/#get-user-info
        * Collect 'account' data (Squid+):
            https://docs.ceph.com/en/latest/radosgw/adminops/#get-account-info
        """

        start = time.time()
        self._errors = 0
        self._setup_empty_prometheus_metrics()

        users = {}
        buckets = []
        accounts = {}

        # Users go first: their account_id is needed to map buckets and
        # usage entries to accounts.
        if self.collectors & {"users", "accounts"}:
            users = self._get_rgw_users()

        # Bucket stats are also required to aggregate account usage.
        if self.collectors & {"buckets", "accounts"}:
            rgw_bucket = self._request_data("bucket", {"stats": "True"})
            if isinstance(rgw_bucket, list):
                buckets = [b for b in rgw_bucket if isinstance(b, dict)]
            up = rgw_bucket is not None
        else:
            up = True

        if "accounts" in self.collectors:
            accounts = self._get_rgw_accounts(users, buckets)

        if "usage" in self.collectors:
            rgw_usage = self._request_data(
                "usage", {"show-entries": "True", "show-summary": "False"}
            )
            if rgw_usage:
                self._update_usage_metrics(
                    self._aggregate_usage(rgw_usage), users, accounts
                )

        if "buckets" in self.collectors:
            for bucket in buckets:
                self._update_bucket_metrics(bucket, users, accounts)

        if "users" in self.collectors:
            for uid, info in users.items():
                self._update_user_metrics(uid, info)

        if "accounts" in self.collectors:
            self._update_account_metrics(accounts, users, buckets)

        duration = time.time() - start
        logging.info(
            "Collected %d users, %d buckets, %d accounts in %.1fs (%d errors)",
            len(users),
            len(buckets),
            len(accounts),
            duration,
            self._errors,
        )

        self._prometheus_metrics["up"].add_metric([self.store], 1 if up else 0)
        self._prometheus_metrics["scrape_errors"].add_metric([self.store], self._errors)
        self._prometheus_metrics["scrape_duration_seconds"].add_metric([], duration)
        self._prometheus_metrics["scrape_timestamp"].add_metric([], time.time())
        self._prometheus_metrics["users_collected"].add_metric(
            [self.store], len(users)
        )

        for metric in list(self._prometheus_metrics.values()):
            yield metric

    def _session(self):
        """
        Setup Requests connection settings.
        """
        self.session = requests.Session()
        # With thousands of per-user requests, transient errors (RGW busy,
        # proxy hiccups) are expected: retry them with backoff.
        retry = Retry(
            total=self.retries,
            backoff_factor=0.5,
            status_forcelist=(429, 500, 502, 503, 504),
            allowed_methods=("GET",),
            raise_on_status=False,
        )
        self.session_adapter = requests.adapters.HTTPAdapter(
            pool_connections=self.threads, pool_maxsize=self.threads, max_retries=retry
        )
        self.session.mount("http://", self.session_adapter)
        self.session.mount("https://", self.session_adapter)
        self.session.verify = not self.insecure

        if self.insecure:
            warnings.filterwarnings("ignore", message="Unverified HTTPS request")
            logging.debug("Perform insecure requests")

    def _request_data(self, query, params=None):
        """
        Requests data from RGW. If admin entry and caps is fine - return
        JSON data, otherwise return NoneType.
        """
        url = "{0}{1}".format(self.url, query)
        params = dict(params or {})
        params["format"] = "json"

        try:
            response = self.session.get(
                url, params=params, timeout=self.timeout, auth=self.auth
            )

            if response.status_code == requests.codes.ok:
                logging.debug("GET %s -> %s", response.url, response.status_code)
                return response.json()

            # Usage caps absent, wrong admin entry or unsupported API
            logging.error(
                "Request error [%s] %s: %s",
                response.status_code,
                response.url,
                response.content.decode("utf-8", "replace"),
            )

        # DNS, connection errors, invalid JSON, etc
        except (requests.exceptions.RequestException, ValueError) as e:
            logging.error("Request error %s: %s", url, e)

        with self._lock:
            self._errors += 1
        return None

    def _setup_empty_prometheus_metrics(self):
        """
        The metrics we want to export.
        """

        u_labels = ["bucket", "owner", "account", "category", "store"]
        b_labels = ["bucket", "owner", "account", "tenant", "zonegroup", "store"]
        b_labels += [_tag_label(t) for t in self.tags]
        user_labels = ["user", "account", "store"]
        acc_labels = ["account", "store"]

        def counter(name, doc, labels):
            return CounterMetricFamily(name, doc, labels=labels)

        def gauge(name, doc, labels):
            return GaugeMetricFamily(name, doc, labels=labels)

        self._prometheus_metrics = {
            # Usage log
            "ops": counter(
                "radosgw_usage_ops_total", "Number of operations", u_labels
            ),
            "successful_ops": counter(
                "radosgw_usage_successful_ops_total",
                "Number of successful operations",
                u_labels,
            ),
            "bytes_sent": counter(
                "radosgw_usage_sent_bytes_total", "Bytes sent by the RADOSGW", u_labels
            ),
            "bytes_received": counter(
                "radosgw_usage_received_bytes_total",
                "Bytes received by the RADOSGW",
                u_labels,
            ),
            # Buckets
            "bucket_usage_bytes": gauge(
                "radosgw_usage_bucket_bytes", "Bucket used bytes", b_labels
            ),
            "bucket_utilized_bytes": gauge(
                "radosgw_usage_bucket_utilized_bytes",
                "Bucket utilized bytes",
                b_labels,
            ),
            "bucket_usage_objects": gauge(
                "radosgw_usage_bucket_objects", "Number of objects in bucket", b_labels
            ),
            "bucket_quota_enabled": gauge(
                "radosgw_usage_bucket_quota_enabled",
                "Quota enabled for bucket",
                b_labels,
            ),
            "bucket_quota_max_size": gauge(
                "radosgw_usage_bucket_quota_size",
                "Maximum allowed bucket size",
                b_labels,
            ),
            "bucket_quota_max_size_bytes": gauge(
                "radosgw_usage_bucket_quota_size_bytes",
                "Maximum allowed bucket size in bytes",
                b_labels,
            ),
            "bucket_quota_max_objects": gauge(
                "radosgw_usage_bucket_quota_size_objects",
                "Maximum allowed bucket size in number of objects",
                b_labels,
            ),
            "bucket_shards": gauge(
                "radosgw_usage_bucket_shards", "Number of shards in bucket", b_labels
            ),
            # Users
            "user_metadata": gauge(
                "radosgw_user_metadata",
                "User metadata",
                [
                    "user",
                    "display_name",
                    "email",
                    "storage_class",
                    "account",
                    "type",
                    "store",
                ],
            ),
            "user_suspended": gauge(
                "radosgw_usage_user_suspended", "User is suspended", user_labels
            ),
            "user_quota_enabled": gauge(
                "radosgw_usage_user_quota_enabled", "User quota enabled", user_labels
            ),
            "user_quota_max_size": gauge(
                "radosgw_usage_user_quota_size",
                "Maximum allowed size for user",
                user_labels,
            ),
            "user_quota_max_size_bytes": gauge(
                "radosgw_usage_user_quota_size_bytes",
                "Maximum allowed size in bytes for user",
                user_labels,
            ),
            "user_quota_max_objects": gauge(
                "radosgw_usage_user_quota_size_objects",
                "Maximum allowed number of objects across all user buckets",
                user_labels,
            ),
            "user_bucket_quota_enabled": gauge(
                "radosgw_usage_user_bucket_quota_enabled",
                "User per-bucket-quota enabled",
                user_labels,
            ),
            "user_bucket_quota_max_size": gauge(
                "radosgw_usage_user_bucket_quota_size",
                "Maximum allowed size for each bucket of user",
                user_labels,
            ),
            "user_bucket_quota_max_size_bytes": gauge(
                "radosgw_usage_user_bucket_quota_size_bytes",
                "Maximum allowed size bytes size for each bucket of user",
                user_labels,
            ),
            "user_bucket_quota_max_objects": gauge(
                "radosgw_usage_user_bucket_quota_size_objects",
                "Maximum allowed number of objects in each user bucket",
                user_labels,
            ),
            "user_total_objects": gauge(
                "radosgw_usage_user_total_objects",
                "Usage of objects by user",
                user_labels,
            ),
            "user_total_bytes": gauge(
                "radosgw_usage_user_total_bytes", "Usage of bytes by user", user_labels
            ),
            # Accounts (Squid+)
            "account_metadata": gauge(
                "radosgw_account_metadata",
                "Account metadata",
                ["account", "name", "email", "tenant", "store"],
            ),
            "account_quota_enabled": gauge(
                "radosgw_usage_account_quota_enabled",
                "Account quota enabled",
                acc_labels,
            ),
            "account_quota_max_size": gauge(
                "radosgw_usage_account_quota_size",
                "Maximum allowed size for account",
                acc_labels,
            ),
            "account_quota_max_size_bytes": gauge(
                "radosgw_usage_account_quota_size_bytes",
                "Maximum allowed size in bytes for account",
                acc_labels,
            ),
            "account_quota_max_objects": gauge(
                "radosgw_usage_account_quota_size_objects",
                "Maximum allowed number of objects across all account buckets",
                acc_labels,
            ),
            "account_bucket_quota_enabled": gauge(
                "radosgw_usage_account_bucket_quota_enabled",
                "Account per-bucket-quota enabled",
                acc_labels,
            ),
            "account_bucket_quota_max_size": gauge(
                "radosgw_usage_account_bucket_quota_size",
                "Maximum allowed size for each bucket of account",
                acc_labels,
            ),
            "account_bucket_quota_max_size_bytes": gauge(
                "radosgw_usage_account_bucket_quota_size_bytes",
                "Maximum allowed size in bytes for each bucket of account",
                acc_labels,
            ),
            "account_bucket_quota_max_objects": gauge(
                "radosgw_usage_account_bucket_quota_size_objects",
                "Maximum allowed number of objects in each account bucket",
                acc_labels,
            ),
            "account_max_users": gauge(
                "radosgw_usage_account_max_users",
                "Maximum number of users in account",
                acc_labels,
            ),
            "account_max_roles": gauge(
                "radosgw_usage_account_max_roles",
                "Maximum number of roles in account",
                acc_labels,
            ),
            "account_max_groups": gauge(
                "radosgw_usage_account_max_groups",
                "Maximum number of groups in account",
                acc_labels,
            ),
            "account_max_buckets": gauge(
                "radosgw_usage_account_max_buckets",
                "Maximum number of buckets in account",
                acc_labels,
            ),
            "account_max_access_keys": gauge(
                "radosgw_usage_account_max_access_keys",
                "Maximum number of access keys per user in account",
                acc_labels,
            ),
            "account_users": gauge(
                "radosgw_usage_account_users",
                "Number of users in account",
                acc_labels,
            ),
            "account_buckets": gauge(
                "radosgw_usage_account_buckets",
                "Number of buckets owned by account",
                acc_labels,
            ),
            "account_total_objects": gauge(
                "radosgw_usage_account_total_objects",
                "Usage of objects by account",
                acc_labels,
            ),
            "account_total_bytes": gauge(
                "radosgw_usage_account_total_bytes",
                "Usage of bytes by account",
                acc_labels,
            ),
            "account_total_utilized_bytes": gauge(
                "radosgw_usage_account_total_utilized_bytes",
                "Utilized (after compression) bytes by account",
                acc_labels,
            ),
            # Exporter
            "up": gauge(
                "radosgw_usage_up",
                "Whether the RGW admin API could be queried",
                ["store"],
            ),
            "scrape_errors": gauge(
                "radosgw_usage_scrape_errors",
                "Number of failed admin API requests during the last scrape",
                ["store"],
            ),
            "scrape_duration_seconds": gauge(
                "radosgw_usage_scrape_duration_seconds",
                "Amount of time each scrape takes",
                [],
            ),
            "scrape_timestamp": gauge(
                "radosgw_usage_scrape_timestamp_seconds",
                "Unix time when the last collection from RGW finished",
                [],
            ),
            "users_collected": gauge(
                "radosgw_usage_users_collected",
                "Number of users whose info was collected in the last scrape",
                ["store"],
            ),
        }

    # ------------------------------------------------------------------
    # Ownership helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _account_of(owner, users, accounts):
        """
        Resolve the account an owner belongs to. Buckets created by account
        users are owned by the account itself; buckets of regular users are
        owned by the user, who may be a member of an account.
        """
        if owner in accounts or ACCOUNT_ID_RE.match(owner or ""):
            return owner
        info = users.get(owner) or {}
        return info.get("account_id") or ""

    # ------------------------------------------------------------------
    # Usage log
    # ------------------------------------------------------------------

    @staticmethod
    def _aggregate_usage(rgw_usage):
        """
        Builds a dictionary of usage counters keyed by (owner, bucket,
        category) in order to handle owners whose usage data is split into
        multiple entries / bins.
        """
        usage = defaultdict(Counter)

        for entry in rgw_usage.get("entries", []):
            bucket_owner = entry.get("owner") or entry.get("user") or ""

            for bucket in entry.get("buckets", []):
                logging.debug(json.dumps(bucket, indent=4, sort_keys=True))
                bucket_name = bucket.get("bucket") or "bucket_root"

                for category in bucket.get("categories", []):
                    usage[(bucket_owner, bucket_name, category["category"])].update(
                        {
                            "ops": category.get("ops", 0),
                            "successful_ops": category.get("successful_ops", 0),
                            "bytes_sent": category.get("bytes_sent", 0),
                            "bytes_received": category.get("bytes_received", 0),
                        }
                    )
        return usage

    def _update_usage_metrics(self, usage, users, accounts):
        """
        Update prometheus metrics with bucket usage data
        """
        for (owner, bucket, category), data in usage.items():
            labels = [
                bucket,
                owner,
                self._account_of(owner, users, accounts),
                category,
                self.store,
            ]
            for key in ("ops", "successful_ops", "bytes_sent", "bytes_received"):
                self._prometheus_metrics[key].add_metric(labels, data[key])

    # ------------------------------------------------------------------
    # Buckets
    # ------------------------------------------------------------------

    @staticmethod
    def _bucket_main_usage(bucket):
        """
        Return (bytes, utilized_bytes, objects) from 'rgw.main' usage.
        """
        main = (bucket.get("usage") or {}).get("rgw.main") or {}
        # Prefer bytes, instead kbytes
        if "size_actual" in main:
            size = main["size_actual"]
        else:
            size = main.get("size_kb_actual", 0) * 1024
        return size, main.get("size_utilized", 0), main.get("num_objects", 0)

    def _bucket_tag_values(self, bucket):
        """
        Return one value per configured tag (empty string when absent) so
        label values always line up with label names.
        """
        tagset = bucket.get("tagset") or {}
        # Some releases return a list of {"key": .., "val"/"value": ..}
        if isinstance(tagset, list):
            tagset = {
                t.get("key"): t.get("val", t.get("value", ""))
                for t in tagset
                if isinstance(t, dict)
            }
        return [str(tagset.get(t, "")) for t in self.tags]

    def _update_bucket_metrics(self, bucket, users, accounts):
        """
        Method get actual bucket usage (in bytes).
        """
        logging.debug(json.dumps(bucket, indent=4, sort_keys=True))

        owner = bucket.get("owner", "")
        size, utilized, objects = self._bucket_main_usage(bucket)

        labels = [
            bucket.get("bucket", ""),
            owner,
            self._account_of(owner, users, accounts),
            bucket.get("tenant", ""),
            bucket.get("zonegroup", "0"),
            self.store,
        ] + self._bucket_tag_values(bucket)

        m = self._prometheus_metrics
        m["bucket_usage_bytes"].add_metric(labels, size)
        m["bucket_utilized_bytes"].add_metric(labels, utilized)
        m["bucket_usage_objects"].add_metric(labels, objects)
        m["bucket_shards"].add_metric(labels, _num(bucket.get("num_shards")))

        quota = bucket.get("bucket_quota")
        if quota:
            self._add_quota(labels, quota, "bucket_quota")

    def _add_quota(self, labels, quota, prefix):
        m = self._prometheus_metrics
        m[prefix + "_enabled"].add_metric(labels, _num(quota.get("enabled")))
        m[prefix + "_max_size"].add_metric(labels, _num(quota.get("max_size"), -1))
        m[prefix + "_max_size_bytes"].add_metric(
            labels, _num(quota.get("max_size_kb")) * 1024
        )
        m[prefix + "_max_objects"].add_metric(
            labels, _num(quota.get("max_objects"), -1)
        )

    # ------------------------------------------------------------------
    # Users
    # ------------------------------------------------------------------

    def _list_keys(self, query, params=None):
        """
        Fetch every key of a paginated listing ('user?list' or
        'metadata/<section>'). RGW caps each page at 'max-entries' (1000 by
        default) and returns {"keys": [...], "truncated": bool, "marker": ..};
        the marker is an opaque cursor passed back as-is. Older releases
        return a plain list with everything.

        Returns None when the first page fails, so callers can fall back.
        """
        params = dict(params or {})
        params["max-entries"] = str(LIST_PAGE_SIZE)
        keys, seen, seen_markers = [], set(), set()

        while True:
            page = self._request_data(query, params)
            if page is None:
                if not keys:
                    return None
                logging.error(
                    "Listing %s stopped after %d keys: page request failed",
                    query,
                    len(keys),
                )
                return keys
            if isinstance(page, list):
                page_keys, truncated, marker = page, False, None
            elif isinstance(page, dict) and "keys" in page:
                page_keys = page["keys"]
                truncated = page.get("truncated", False)
                marker = page.get("marker")
            else:
                return keys or None

            new = [k for k in page_keys if k not in seen]
            seen.update(new)
            keys.extend(new)
            logging.debug("Listing %s: %d keys so far", query, len(keys))

            if not truncated:
                return keys
            if not marker or marker in seen_markers or not new:
                # Guard against RGW releases returning a missing or
                # repeating marker, which would loop forever.
                logging.error(
                    "Listing %s is truncated but pagination did not advance "
                    "(marker=%r); returning %d keys",
                    query,
                    marker,
                    len(keys),
                )
                return keys
            seen_markers.add(marker)
            params["marker"] = marker

    def _list_rgw_users(self):
        """
        List all user IDs, following pagination markers.
        """
        uids = self._list_keys("user", {"list": ""})
        if uids is None:
            # Compat with old Ceph versions (pre 12.2.13/13.2.9)
            uids = self._list_keys("metadata/user")
        return uids or []

    def _get_rgw_users(self):
        """
        Returns {uid: user_info} for all users.
        """
        uids = self._list_rgw_users()

        def fetch(uid):
            return uid, self._request_data("user", {"uid": uid, "stats": "True"})

        with ThreadPoolExecutor(max_workers=self.threads) as pool:
            return {uid: info for uid, info in pool.map(fetch, uids) if info}

    def _update_user_metrics(self, uid, user_info):
        """
        Method to get the info on a specific user(s).
        """
        logging.debug(json.dumps(user_info, indent=4, sort_keys=True))

        account = user_info.get("account_id", "")
        labels = [uid, account, self.store]
        m = self._prometheus_metrics

        m["user_metadata"].add_metric(
            [
                uid,
                user_info.get("display_name", ""),
                user_info.get("email", ""),
                # Nautilus+
                user_info.get("default_storage_class", ""),
                # Squid+
                account,
                user_info.get("type", ""),
                self.store,
            ],
            1,
        )
        m["user_suspended"].add_metric(labels, _num(user_info.get("suspended")))

        stats = user_info.get("stats")
        if stats:
            size = stats.get("size_actual", stats.get("size_kb_actual", 0) * 1024)
            m["user_total_bytes"].add_metric(labels, size)
            m["user_total_objects"].add_metric(labels, stats.get("num_objects", 0))

        if user_info.get("user_quota"):
            self._add_quota(labels, user_info["user_quota"], "user_quota")

        if user_info.get("bucket_quota"):
            self._add_quota(labels, user_info["bucket_quota"], "user_bucket_quota")

    # ------------------------------------------------------------------
    # Accounts (Squid+)
    # ------------------------------------------------------------------

    def _get_rgw_accounts(self, users, buckets):
        """
        Returns {account_id: account_info}. Account IDs are discovered from
        the metadata API and, as a fallback, from user and bucket ownership.
        """
        ids = set()

        ids.update(self._list_keys("metadata/account") or [])

        ids.update(i["account_id"] for i in users.values() if i.get("account_id"))
        ids.update(
            b["owner"] for b in buckets if ACCOUNT_ID_RE.match(b.get("owner", ""))
        )

        def fetch(account_id):
            return account_id, self._request_data("account", {"id": account_id})

        with ThreadPoolExecutor(max_workers=self.threads) as pool:
            fetched = dict(pool.map(fetch, sorted(ids)))

        # Keep accounts even if 'account' info could not be fetched (e.g.
        # missing 'accounts=read' cap) so aggregated usage is still exported.
        return {aid: info or {} for aid, info in fetched.items()}

    def _update_account_metrics(self, accounts, users, buckets):
        m = self._prometheus_metrics

        user_count = Counter(
            i["account_id"] for i in users.values() if i.get("account_id")
        )
        bucket_count = Counter()
        total = defaultdict(Counter)
        for bucket in buckets:
            owner = bucket.get("owner", "")
            if owner not in accounts:
                continue
            size, utilized, objects = self._bucket_main_usage(bucket)
            bucket_count[owner] += 1
            total[owner].update(
                {"bytes": size, "utilized": utilized, "objects": objects}
            )

        for account_id, info in accounts.items():
            logging.debug(json.dumps(info, indent=4, sort_keys=True))
            labels = [account_id, self.store]

            m["account_metadata"].add_metric(
                [
                    account_id,
                    info.get("name", ""),
                    info.get("email", ""),
                    info.get("tenant", ""),
                    self.store,
                ],
                1,
            )

            if info.get("quota"):
                self._add_quota(labels, info["quota"], "account_quota")
            if info.get("bucket_quota"):
                self._add_quota(labels, info["bucket_quota"], "account_bucket_quota")

            for key in ("users", "roles", "groups", "buckets", "access_keys"):
                if "max_" + key in info:
                    m["account_max_" + key].add_metric(
                        labels, _num(info["max_" + key])
                    )

            m["account_users"].add_metric(labels, user_count[account_id])
            m["account_buckets"].add_metric(labels, bucket_count[account_id])
            m["account_total_bytes"].add_metric(labels, total[account_id]["bytes"])
            m["account_total_utilized_bytes"].add_metric(
                labels, total[account_id]["utilized"]
            )
            m["account_total_objects"].add_metric(labels, total[account_id]["objects"])


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ("1", "true", "yes", "on")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Prometheus exporter for Ceph RADOSGW usage, bucket, "
        "user and account metrics"
    )
    parser.add_argument(
        "-H",
        "--host",
        required=False,
        help="Server URL for the RADOSGW api (example: http://objects.dreamhost.com/)",
        default=os.environ.get("RADOSGW_SERVER", "http://radosgw:80"),
    )
    parser.add_argument(
        "-e",
        "--admin-entry",
        required=False,
        help="The entry point for an admin request URL [default is '%(default)s']",
        default=os.environ.get("ADMIN_ENTRY", "admin"),
    )
    parser.add_argument(
        "-a",
        "--access-key",
        required=False,
        help="S3 access key",
        default=os.environ.get("ACCESS_KEY", "NA"),
    )
    parser.add_argument(
        "-s",
        "--secret-key",
        required=False,
        help="S3 secret key",
        default=os.environ.get("SECRET_KEY", "NA"),
    )
    parser.add_argument(
        "-k",
        "--insecure",
        help="Allow insecure server connections when using SSL",
        action="store_true",
        default=_env_bool("INSECURE"),
    )
    parser.add_argument(
        "-p",
        "--port",
        required=False,
        type=int,
        help="Port to listen",
        default=int(os.environ.get("VIRTUAL_PORT", "9242")),
    )
    parser.add_argument(
        "-S",
        "--store",
        required=False,
        help="Store name added to metrics",
        default=os.environ.get("STORE", "us-east-1"),
    )
    parser.add_argument(
        "-t",
        "--timeout",
        required=False,
        help="Timeout when getting metrics",
        default=os.environ.get("TIMEOUT", "60"),
    )
    parser.add_argument(
        "-l",
        "--log-level",
        required=False,
        help="Provide logging level: DEBUG, INFO, WARNING, ERROR or CRITICAL",
        default=os.environ.get("LOG_LEVEL", "INFO"),
    )
    parser.add_argument(
        "-T",
        "--tag-list",
        required=False,
        help="Add bucket tags as label (example: 'tag1,tag2,tag3') ",
        default=os.environ.get("TAG_LIST", ""),
    )
    parser.add_argument(
        "--signature",
        required=False,
        choices=["v2", "v4"],
        help="AWS signature version used to sign admin requests [default is '%(default)s']",
        default=os.environ.get("SIGNATURE", "v4"),
    )
    parser.add_argument(
        "--region",
        required=False,
        help="Region used for AWS signature v4 [default is '%(default)s']",
        default=os.environ.get("REGION", "us-east-1"),
    )
    parser.add_argument(
        "--threads",
        required=False,
        type=int,
        help="Number of parallel requests for user/account info [default is '%(default)s']",
        default=int(os.environ.get("THREADS", "10")),
    )
    parser.add_argument(
        "-c",
        "--collectors",
        required=False,
        help="Comma separated collectors to enable: usage,buckets,users,accounts "
        "[default is '%(default)s']",
        default=os.environ.get("COLLECTORS", ",".join(ALL_COLLECTORS)),
    )
    parser.add_argument(
        "-i",
        "--interval",
        required=False,
        type=float,
        help="Collect from RGW in the background every N seconds and serve "
        "cached metrics; 0 queries RGW on every scrape [default is '%(default)s']",
        default=float(os.environ.get("INTERVAL", "60")),
    )
    parser.add_argument(
        "--retries",
        required=False,
        type=int,
        help="Retries for failed admin API requests [default is '%(default)s']",
        default=int(os.environ.get("RETRIES", "3")),
    )

    args = parser.parse_args()
    args.collectors = [c.strip() for c in args.collectors.split(",") if c.strip()]
    unknown = set(args.collectors) - set(ALL_COLLECTORS)
    if unknown:
        parser.error("unknown collectors: {0}".format(", ".join(sorted(unknown))))
    return args


def main():
    try:
        args = parse_args()
        logging.basicConfig(level=args.log_level.upper())
        collector = RADOSGWCollector(
            args.host,
            args.admin_entry,
            args.access_key,
            args.secret_key,
            args.store,
            args.insecure,
            args.timeout,
            args.tag_list,
            signature=args.signature,
            region=args.region,
            threads=args.threads,
            collectors=args.collectors,
            interval=args.interval,
            retries=args.retries,
        )
        REGISTRY.register(collector)
        collector.start_background()
        start_http_server(args.port, addr="::")
        logging.info("Polling %s. Serving at port: %s", args.host, args.port)
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        logging.info("Interrupted")
        sys.exit(0)


if __name__ == "__main__":
    main()
